export const productsPage = {
    inventoryItem: ".inventory_item",
    inventoryItemName: ".inventory_item_name",
    inventoryItemPrice: ".inventory_item_price",
    addToCartButton: "Add to cart",
    cartBadge: ".shopping_cart_link",
    cartItem: ".cart_item",
    removeButton: "Remove",
    checkoutButton: "#checkout",
    firstNameInput: "#first-name",
    lastNameInput: "#last-name",
    postalCodeInput: "#postal-code",
    continueButton: "#continue",
    checkoutAlert: "h3[data-test='error']",
    subtotalLabel: ".summary_subtotal_label",
    taxLabel: ".summary_tax_label",
    totalLabel: ".summary_total_label",
    finishButton: "#finish",
    successMessage: ".complete-header",
};